Models/Categoria.cs
namespace CSharpEF.Models
{
    public class Categoria
    {
        public int Id { get; set; }
        public string Nome { get; set; }

        public override string ToString()
        {
            return $"Id: {this.Id} | Nome: {this.Nome}";
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace CSharpEF.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Funcionario.cs
namespace CSharpEF.Models
{
    public class Funcionario
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public float Salario { get; set; }
        public string Cpf { get; set; }
    }
}

Models/Produto.cs
namespace CSharpEF.Models
{
    public class Produto
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public virtual Categoria Categoria { get; set; }

        public override string ToString()
        {
            return $"Id: {Id} | Nome: {Nome} | Categoria: {Categoria.ToString()}";
        }
    }
}

Controllers/FuncionarioController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;

using CSharpEF.Models;
using CSharpEF.Database;

namespace CSharpEF.Database
{
    public class FuncionarioController : Controller
    {
        private readonly ApplicationDBContext database;

        public FuncionarioController(ApplicationDBContext database)
        {
            this.database = database;
        }

        public IActionResult Index()
        {
            var funcionarios = database.Funcionarios.ToList();
            return View(funcionarios);
        }

        public IActionResult Cadastrar() 
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            //Funcionario funcionario = database.Funcionarios.First(registro => registro.Id == id);
            Funcionario funcionario = database.Funcionarios.Find(id);
            return View("Cadastrar", funcionario);
        }

        public IActionResult Deletar(int id) 
        {
            Funcionario funcionario = database.Funcionarios.Find(id);
            database.Funcionarios.Remove(funcionario);
            database.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Salvar(Funcionario funcionario)
        {
            if (funcionario.Id == 0) {
                // Salva novo
                database.Funcionarios.Add(funcionario);
            } else {
                // Atualizar funcionario
                Funcionario funcionarioDb = database.Funcionarios.Find(funcionario.Id);
                funcionarioDb.Nome    = funcionario.Nome;
                funcionarioDb.Salario = funcionario.Salario;
                funcionarioDb.Cpf     = funcionario.Cpf;
            }

            database.SaveChanges();
            return RedirectToAction("Index");
        }
    }

}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CSharpEF.Models;
using CSharpEF.Database;
using Microsoft.EntityFrameworkCore;

namespace CSharpEF.Controllers
{
    public class HomeController : Controller
    {

        private readonly ApplicationDBContext database;

        private readonly ILogger<HomeController> _logger;

        public HomeController(ApplicationDBContext database)
        {
            this.database = database;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Teste()
        {
            /*
            Categoria c1 = new Categoria();
            Categoria c2 = new Categoria();
            Categoria c3 = new Categoria();
            Categoria c4 = new Categoria();
            
            c1.Nome = "Aluno";
            c2.Nome = "Professor";
            c3.Nome = "Monitor";
            c4.Nome = "Monitor";

            List<Categoria> lstCategoria = new List<Categoria>();

            lstCategoria.Add(c1);
            lstCategoria.Add(c2);
            lstCategoria.Add(c3);
            lstCategoria.Add(c4);

            database.AddRange(lstCategoria);
            database.SaveChanges();
            */

            // Console.Write("");

            Console.WriteLine("==============================================");

            var lstCategoria = database.Categorias.Where(cat => cat.Nome.Equals("Monitor")).ToList();

            foreach (var categoria in lstCategoria)
            {
                Console.WriteLine(categoria.ToString());
            }

            Console.WriteLine("==============================================");

            return Content("Dados salvos");
        }

        public IActionResult Produtos()
        {
            Console.WriteLine("==============================================");

            // var lstProduto = database.Produtos.Include(p => p.Categoria).ToList();

            // Consulta Lazy Loding - sem include
            var lstProduto = database.Produtos.ToList();

            foreach (var produto in lstProduto)
            {
                Console.WriteLine(produto.ToString());
            }

            Console.WriteLine("==============================================");

            return Content("Listando Produtos");
        }

        public IActionResult ProdutosCategoria(int id)
        {
            Console.WriteLine("==============================================");

            var lstProduto = database.Produtos.Include(p => p.Categoria).Where(p => p.Categoria.Id == id).ToList();

            foreach (var produto in lstProduto)
            {
                Console.WriteLine(produto.ToString());
            }

            Console.WriteLine("==============================================");

            return Content("Dados salvos");
        }        

        public IActionResult Relacionamento() 
        {
            Produto p = new Produto();
            p.Nome = "Doritos";
            p.Categoria = database.Categorias.Find(1);

            Produto p2 = new Produto();
            p2.Nome = "Frango";
            p2.Categoria = database.Categorias.Find(1);

            Produto p3 = new Produto();
            p3.Nome = "Bolo";
            p3.Categoria = database.Categorias.Find(2);

            database.Add(p);
            database.Add(p2);
            database.Add(p3);

            database.SaveChanges();

            return Content("Relacionamento");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Funcionario/Cadastrar.cshtml
@model CSharpEF.Models.Funcionario

<h2>Cadastro de Funcionários</h2>

<form class="form-horizontal" asp-controller="Funcionario" asp-action="Salvar" method="POST">
    <input type="hidden" asp-for="Id">
    <input type="text"   class="form-control" asp-for="Nome"    placeholder="Nome">
    <input type="number" class="form-control" asp-for="Salario" placeholder="Salário">
    <input type="text"   class="form-control" asp-for="Cpf"     placeholder="CPF">
    <button class="btn btn-primary">Cadastrar</button>
</form>

Views/Funcionario/Index.cshtml
@model IEnumerable<CSharpEF.Models.Funcionario>

<h2>Todos os Funcionários</h2>

<a href="/Funcionario/Cadastrar" class="btn btn-primary">Novo Funcionário</a>
<hr>
@foreach (var funcionario in Model)
{
    <p>CPF: @funcionario.Cpf</p>
    <p>Nome: @funcionario.Nome</p>
    <p>Salário: @funcionario.Salario</p>
    <a href="/Funcionario/Editar/@funcionario.Id" class="btn btn-info">Editar</a>
    <a href="/Funcionario/Deletar/@funcionario.Id" class="btn btn-danger">Deletar</a>
    <hr>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSharpEF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CSharpEF</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CSharpEF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>